# Generated by Django 5.1.1 on 2024-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem", unique_together={("name", "description")},
        ),
    ]
